<template>
    <div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
        <div>这是switch的内容</div>
    </div>
</template>

<script lang="ts">
export default ({
    name:'SwitchDemo'
})
</script>